config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', verification_user, name='verification'),
    path('success_verification/', success_verification, name='success_verification'),
    path('reset_password/', set_new_password, name='reset_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=40, verbose_name='страна')
    key = models.IntegerField(verbose_name='ключ', **NULLABLE)
    is_active = models.BooleanField(verbose_name='признак верификации', default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "available":
                field.widget.attrs['class'] = 'form-control'


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class VerificationForm(forms.Form):
    key = forms.IntegerField(label='Введите ключ для верификации')


class ResetPasswordForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = ('email',)

users/views.py
import random

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView as BaseLoginView

from users.forms import *
from users.models import User
from users.services import *


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save()
        user.save()

        key = random.randint(1000, 9999)
        self.request.session['key'] = key
        user_email = self.request.POST.get('email')
        send_verification_mail(user_email, key)

        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:verification')


def verification_user(request):
    key = request.session.get('key')
    user = request.user
    if request.method == 'POST':
        form = VerificationForm(request.POST)
        if form.is_valid():
            entered_key = form.cleaned_data['key']
            if entered_key == key:
                user.is_active = True
                return redirect('users:success_verification')
    else:
        form = VerificationForm()
    return render(request, 'users/verification.html', {'form': form})


def success_verification(request):
    return render(request, 'users/verification_success.html')


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('catalog:product')


@login_required
def set_new_password(request):
    form = ResetPasswordForm()
    if request.method == 'POST':
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        user_email = request.user.email
        send_new_password(user_email, new_password)
        request.user.set_password(new_password)
        request.user.save()
    return render(request, 'users/password_reset.html', {'form': form})

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Вход
        </div>
        <form method="post" class="row">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
                <a href="{% url 'users:reset_password' %}" class="btn btn-sm btn-outline-scondary">Забыли пароль?
                    Восстановить</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Восстановление пароля
        </div>
        <form method="post" class="row">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Подтвердить
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Регистрация
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Подтвердить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/verification.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Верификация
        </div>
        <form method="post" class="row">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Подтвердить
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/verification_success.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Верификация успешна пройдена!</h1>
</div>

{% endblock %}